# Generated by Django 4.2.7 on 2023-11-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_No', models.IntegerField()),
                ('FoodId', models.TextField()),
                ('Item', models.TextField()),
                ('Qty', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalPrice', models.TextField()),
                ('Note', models.TextField(max_length=100, null=True)),
                ('OrderId', models.TextField(max_length=5, null=True)),
                ('food_status', models.CharField(choices=[('1', 'Has been ordered'), ('2', 'cooked'), ('3', 'ready to be served'), ('4', 'done')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='course',
        ),
        migrations.RemoveField(
            model_name='new',
            name='department',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
