# Generated by Django 4.2.7 on 2023-11-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_reg_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
