# Generated by Django 4.2.7 on 2023-11-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_alter_reg_cpassword_alter_reg_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
